sonar.projectKey=Corei913th_enrolcm_api
sonar.organization=corei913th
sonar.projectName=enrolcm_api
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.php.tests.reportPath=build/logs/clover.xml
sonar.php.coverage.reportPaths=build/logs/clover.xml

sonar.exclusions=vendor/**, tests/**, database/**, config/**, public/**
sonar.sourceEncoding=UTF-8
