route:
  group_by: [ "alertname" ]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "email-notifications"
receivers:
  - name: "email-notifications"
    email_configs:
      - to: bogningfredy972@gmail.com
        from: bogningfredy972@gmail.com
        smarthost: "smtp.gmail.com:587"
        auth_username: bogningfredy972@gmail.com
        auth_password: utsq exdn nfcp dnga
