input {
  beats {
    port => 5044
  }
}

filter {
  if [container][name] == "enrolcm_app" {
    json {
      source => "message"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "laravel-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
