name: Deploy

on:
  workflow_run:
    workflows: [ "🏗️ CI - Validation" ]
    types:
      - completed
    branches:
      - main

jobs:

  check-ci:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 🔍 CI Validation
        run: echo "CI validated. Proceeding to deploy..."

  deploy:
    name: "🚀 Deploy to Production"
    needs: [ check-ci ]
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: "📝 Préparation du .env et du Flag"
        run: |
          printf '%s' "${{ secrets.PROD_ENV_FILE }}" > .env
          grep -q "^APP_KEY=" .env || echo "APP_KEY=" >> .env
          NEW_KEY=$(php -r "echo 'base64:'.base64_encode(random_bytes(32));")
          sed -i 's|^APP_KEY=.*|APP_KEY='${NEW_KEY}'|' .env
          echo "deploy" > deploy.flag

      - name: "📤 Déploiement Backend via FTP"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: public_html/bogning/enrolcm_api/
          exclude: |
            **/vendor/**
            **/.git*
            **/node_modules/**
            **/tests/**
            **/k8s/**
            **/docker/**

      - name: "✅ Terminé"
        run: echo "Déploiement terminé via FTP dans le dossier api/"
